export const LOADING = 'LOADING'
export const CATEGORY_FINISH = 'CATEGORY_FINISH'

export const PRODUCT = {
    DISCOUNT: 'PRODUCT_DISCOUNT'
}

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FINISH = 'PRODUCT_FINISH'
export const PRODUCT_DETAIL_LOADING = 'PRODUCT_DETAIL_LOADING';
export const PRODUCT_DETAIL_FINISH = 'PRODUCT_DETAIL_FINISH'


// export const USER_LOADING = 'USER_LOADING'
// export const USER_LOGIN = 'USER_LOGIN'
// export const USER_RECEIVE = 'USER_RECEIVE'
// export const USER_FAIL = 'USER_FAIL'
export const USER = {
    LOGOUT: 'USER_LOGOUT',
    FETCH_UPDATE: 'USER_FETCH_UPDATE',
    RECEIVE_UPDATE: 'USER_RECEIVE_UPDATE',
    UPDATE: 'USER_UPATE',
    LOGIN: 'USER_LOGIN',
    LOGIN_RECEIVE: 'USER_LOGIN_RECEIVE',
    LOGIN_FAIL: 'USER_LOGIN_FAIL',
    LOADING: 'USER_LOADING',
    UPDATE_ERROR: 'USER_UPDATE_ERROR',
    REGISTER: 'USER_REGISTER',
    REGISTER_RECEIVE: 'USER_REGISTER_RECEIVE',
    REGISTER_FAIL: 'USER_REGISTER_FAIL',
    ERROR: 'USER_ERROR'
}


export const CART_OPEN = 'CART_OPEN'
export const CART_CLOSE = 'CART_CLOSE'
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_ITEM_INCREMENT = 'CART_ITEM_INCREMENT'
export const CART_ITEM_DECREMENT = 'CART_ITEM_DECREMENT'
export const CART_SHIPPING_OPTION = 'CART_SHIPPING_OPTION'
export const CART_PAYMENT_OPTION = 'CART_PAYMENT_OPTION'